name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch: # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[deploy]') || github.event_name == 'workflow_dispatch'"
    
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 217.154.58.180
          username: justyn
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/justyn/work/n8n-catalog
            echo "🚀 Starting deployment..."
            git pull origin main
            chmod +x deploy-fix.sh
            ./deploy-fix.sh
            echo "✅ Deployment completed"
            
      - name: Verify deployment
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 217.154.58.180
          username: justyn
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/justyn/work/n8n-catalog
            echo "📊 Container status:"
            docker-compose -f docker-compose.prod.yml ps
            echo "📋 Recent logs:"
            docker-compose -f docker-compose.prod.yml logs --tail=10
            
      - name: Test HTTPS endpoint
        run: |
          echo "🔒 Testing HTTPS endpoint..."
          curl -f -s -I https://catalog.fintonlabs.com || exit 1
          echo "✅ HTTPS endpoint is responding"
